In [1]:
import numpy as np
import matplotlib.pyplot as plt


import scipy.io
%matplotlib 

Using matplotlib backend: Qt5Agg


In [2]:
def db2mag(db): return db #20 * np.log10(db)

In [3]:
def BasicFit(adress_file,offs,ang,ph):
    mat = scipy.io.loadmat(adress_file)
    
    f, mag, pha, Gain, SignalGeneratorPumpP = mat['f'],  mat['mag'],  mat['pha'],  mat['Gain'], mat['SignalGeneratorPumpP']
    
    

In [31]:
adress_file = r"C:\Users\mukha\Downloads\Gain_12.084202104232356GHz.mat" 
offs = -0.532e6
ang = 0.233
ph = 0


mat = scipy.io.loadmat(adress_file)
mat.keys()

f, mag, pha, Gain, pows_exper = np.array(mat['f'][0]),  np.array(mat['mag']),  np.array(mat['pha']),  np.array(mat['Gain']), np.array(mat['SignalGeneratorPumpP'][0])

#     f: (4001,)
#   mag: (4001, 102)
#   pha: (4001, 102)
#  Gain: (4001, 35)
#   pow: (102,)

f_mean = f[int(len(f)/2+0.5)]      # f_mean: (1,)
f_mean_2pi = 2*np.pi*f_mean        # f_mean_2pi: (1,)
f_norm = f - f_mean                # f_norm: (4001,)
Gain_redused = Gain[:,1:]          # Gain_redused: (4001, 34)
po = pows_exper[1:]                # po: (101,)

mag_m1colomn = mag-mag[:,0][np.newaxis].T  #  mag_m1colomn: (4001, 102)
mag_db = db2mag(mag_m1colomn)              #     mag_db: (4001, 102)
mag_del1colomn = mag_db[:,1:]              # mag_del1colomn: (4001, 101)

mag_init = db2mag(mag[:,1]-mag[:,0])[np.newaxis].T #  mag_init: (4001, 1)
pha_init = (pha[:,1]-pha[:,0])[np.newaxis].T       #  pha_init: (4001, 1)
pha_m1colomn = pha-pha[:,0][np.newaxis].T          # pha_m1colomn: (4001, 102)
pha_del1colomn = pha[:,1:]                         # pha_del1colomn: (4001, 101)


f_range = (np.linspace(f_norm[0], f_norm[-1], len(f_norm))+offs)*2*np.pi

X = f_norm+offs # X: (4001,)

# for Y: 

E1 = np.exp(-1j*ang*np.pi) # ()
pha_init_T = pha_init.T    # (1, 4001)
mag_init_T = mag_init.T    # (1, 4001)
E2 = np.exp(1j*pha_init_T) # (1, 4001)
S1 = np.multiply(mag_init_T,E2)-1 # (1, 4001) - поэлементное умножение
Y_abs = np.abs(1+np.multiply(E1,S1)) # (1, 4001) 
Y_angle = np.angle(1+np.multiply(E1,S1)) # (1, 4001) 

Y = Y_abs

Xs = mag_init*np.cos(pha_init)
Ys = mag_init*np.sin(pha_init)

ab = np.sqrt(Xs**2+Ys**2)
  
fig, ax = plt.subplots(figsize=(7,7)) 

# ax.plot(X, Y_abs.T, 'r.', color="red")
# ax.plot(Xs, Ys, 'r.', color="red")

ax.plot(f, Gain[:,5], 'r.', color="red")

# ax.plot(f_norm, mag,'.-', markersize = 2,  color="orange")
# ax.plot(f_norm, pha_init*(-1),'.-', markersize = 2,  color="blue")

# ax.plot(f_norm, 20*np.log10(ab),'.-', markersize = 2,  color="lightgreen")
plt.show()

# Y2.shape

C:\Users\mukha\Anaconda3\lib\site-packages\scipy\io\matlab\mio.py:224: MatReadWarning: Duplicate variable name "None" in stream - replacing previous with new
Consider mio5.varmats_from_mat to split file into single variable files
  matfile_dict = MR.get_variables(variable_names)


In [272]:
F1 = pha_init
F2 = mag_init

Y = np.sqrt(F1**2+F2**2)

fig, ax = plt.subplots(figsize=(7,7)) 
ax.plot(f, Y,'.-', markersize = 2,  color="green")
plt.show()


In [105]:
A = np.array([[1,2,3], [4, 5, 6], [7, 8, 9]])
B = A-A[:,0][np.newaxis].T
print(A[:,0], '\n', B)

[1 4 7] 
 [[0 1 2]
 [0 1 2]
 [0 1 2]]


In [16]:
A = np.array([[1,2,3], [4, 5, 6], [7, 8, 9]])
B = np.array([[0,0,0], [0, 0, 0], [0, 0, 0]])
D = np.array([2.3, 5.6, 8.5])
С = dict(zip(, A))
C

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2, 3, 4,
       5, 6, 7, 8, 9, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2, 3, 4, 5, 6, 7, 8,
       9, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [20]:
y = np.abs(3+4*1j)
y

5.0